# Generated by Django 2.2.28 on 2024-03-02 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indie', '0004_auto_20240302_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
