# Generated by Django 2.2.28 on 2024-03-09 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indie', '0005_auto_20240302_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='dev',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='indie.UserProfile'),
        ),
    ]
