# Generated by Django 2.2.28 on 2024-03-10 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indie', '0006_game_dev'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='user',
        ),
        migrations.AddField(
            model_name='feedback',
            name='userProfile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='indie.UserProfile'),
        ),
    ]
