# Generated by Django 2.2.28 on 2024-03-11 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indie', '0007_auto_20240310_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.CharField(blank=True, max_length=9999, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
