# Generated by Django 2.2.28 on 2024-03-12 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indie', '0008_auto_20240311_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='game_images'),
        ),
    ]
