# Generated by Django 2.2.28 on 2024-03-12 01:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('indie', '0009_auto_20240312_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
